"""Single-run walkthroughs — the traces the design document quotes.

`benchmark.md` reports distributions over seeds. The design document also
tells stories ("after the third inspection fail the hypothesis table reads
..."), and those figures come from one specific run. Generating them here
means the story and the code cannot drift apart, and `loom.numbers` can check
the prose against them like anything else.

    python -m loom.trace --out docs/traces.md
"""
from __future__ import annotations

import argparse

from .config import load_line
from .evaluator import containment_scorecard
from .plant import Plant
from .sensors import SensorLayer
from .twin import Twin

H = 3600.0
SEED = 0


def run(config: str, hours: float, seed: int = SEED):
    cfg = load_line(config)
    plant = Plant(cfg)
    plant.rng.seed(seed)
    sensors = SensorLayer(cfg, seed)
    twin = Twin(cfg)
    plant.listeners.append(sensors.observe)
    sensors.subscribers.append(twin.ingest)
    plant.run(hours * H)
    return plant, twin


def multi_cause() -> list[str]:
    plant, twin = run("configs/multi_cause.yaml", 3.0)
    q = twin.quality
    out = ["### `multi_cause.yaml` — two conditions, neither sufficient alone",
           "", f"Seed {SEED}, 3 h. Ranked hypotheses after the inspection fails accumulate:", "",
           "| rank | hypothesis | lift | defective under it | p |", "|---|---|---|---|---|"]
    for i, h in enumerate(q.hypotheses[:4], 1):
        conds = " AND ".join(str(c) for c in h.conditions)
        out.append(f"| {i} | {conds} | {h.lift:.1f}x | {h.a}/{h.a + h.b} vs {h.c}/{h.c + h.d} otherwise "
                   f"| {h.p_value:.2g} |")
    if not q.hypotheses:
        out.append("| - | no hypothesis cleared the significance and lift bars | - | - | - |")
    out += ["", "The decision at each contribution run — what the twin believed a hold's precision",
            "would be, against how many inspection failures it had seen when it believed it:", "",
            "| fails seen | leading hypothesis | posterior | n under it | best rival | action |",
            "|---|---|---|---|---|---|"]
    for r in q.precision_curve:
        rival = " AND ".join(r["rival"]) if r["rival"] else "—"
        rp = "" if r["rival_posterior"] is None else f" ({r['rival_posterior']:.2f})"
        out.append(f"| {r['fails']} | {' AND '.join(r['conditions'])} | {r['posterior']:.2f} "
                   f"| {r['n_under']} | {rival}{rp} | **{r['action']}** |")
    if not q.precision_curve:
        out.append("| - | no contribution run reached the minimum failure count | - | - | - | - |")
    for sr in q.sample_requests[:1]:
        out += ["", f"The abstention is an action, not a shrug: `SAMPLE #{sr.id}` at "
                    f"{sr.t / 60:.1f} min asks for {len(sr.vehicles)} named vehicles at {sr.inspect_at}, "
                    f"chosen because each matches exactly one of the two candidate condition sets, so "
                    f"its result moves the evidence one way rather than being consistent with both."]
    return out


def weld_drift() -> list[str]:
    plant, twin = run("configs/weld_drift_b2.yaml", 2.0)
    q = twin.quality
    out = ["### `weld_drift_b2.yaml` — a silent drift, contained before inspection sees it",
           "", f"Seed {SEED}, 2 h.", "", "| event | line time |", "|---|---|"]
    for a in q.drift_log[:1]:
        out.append(f"| CUSUM warning on {a.station}.{a.param} | {a.t / 60:.1f} min |")
        out.append(f"| estimated drift onset | {a.onset_t / 60:.1f} min |")
    for h in q.holds[:1]:
        out.append(f"| hold #{h.id} opened, {h.size} vehicles | {h.t / 60:.1f} min |")
    for c in containment_scorecard(plant, twin):
        if c.t_first_fail is not None:
            out.append(f"| first end-of-line inspection catch | {c.t_first_fail / 60:.1f} min |")
        out += ["", f"Held {c.hold_size} of the {c.blanket_size} vehicles a blanket hold would stop; "
                    f"{c.true_positives} of them truly defective "
                    f"({(c.precision or 0):.0%} precision, {(c.recall or 0):.0%} recall); "
                    f"{c.escaped} escaped."]
        break
    return out


def report() -> str:
    out = ["# Traces — the single runs the design document quotes", "",
           "Generated by `python -m loom.trace`. `benchmark.md` reports distributions over seeds;",
           "these are the individual runs behind the walkthroughs, so the story and the code cannot",
           "drift apart.", ""]
    out += multi_cause() + [""] + weld_drift()
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    text = report()
    print(text)
    if a.out:
        with open(a.out, "w") as f:
            f.write(text + "\n")


if __name__ == "__main__":
    main()
